
def pkg_deps(ctx):
    return

def options(ctx):
    print("+++++++++>>>> hello from %r" % ctx)
    ctx.load('find_root')

def configure(ctx):
    print("+++++++++++++++++ %r" % ctx.path.abspath())
    return

def build(ctx):
    return
